### ISSUE TITLE
Can't receive Midi Clock messages

### ISSUE THREAD

**Issue by brogli** [keijiro/Minis#25]
I wanted to add the receival of Midi Clock messages, so in my fork I've added a check for status == 0xF8 in MidiPort#ProcessMessageQueue and also added 'RtMidiDll.InIgnoreTypes(_rtmidi, false, false, false);' after RtMidiDll.Openport in the same class (apparently [timing messages are ignored by default by RtMidi](https://stackoverflow.com/a/27668224)). However I'm still not receiving midi clock messages and I don't really see what else could be the problem, do you have an idea by any chance?

The input debugger doesn't detect my device based on the clock messages, only when I send notes/ccs on the same device.

**Comment by keijiro** [comment]
How about testing only with RtMidi? I wonder if there is an issue in integration with the new input system.

**Comment by brogli** [comment]
I've tested with jp.keijiro.RtMidi, and there I can actually receive the clock messages calling RtMidiDll.IgnoreTypes(_rtmidi, true, false, true) after opening the port and then listening for statuscode 0xF and not 0xF8. The latter I've previously tried already. I'll see what I can find out about the input system integration :). Thanks.

**Comment by brogli** [comment]
I've [tried](https://github.com/brogli/Minis/commit/69da4d4ab78029eb7f67a92bd19cad3a7d42a764) handling the midi clock message as the notes and controls are handeled, but the device is still not recognized by Unity. Then again, I don't completely understand what I'm doing. I think I might just use jp.keijiro.RtMidi or go back do MidiJack, as the integration into the new input system isn't that important to me. Do you think MidiJack will not work at some point?

**Comment by keijiro** [comment]
I'd recommend directly using RtMidi if you're okay with it.

I think it's a good way to handle MIDI input devices with the new input system because they're input devices -- Gamepads and MIDI sliders are in the same category. On the other hand, I'm not sure if MIDI clock should be considered in the same category. I don't think there is similarity between a MIDI metronome and a gamepad.

I wouldn't recommend MidJack. It doesn't support some architectures, like Apple silicon.

**Comment by brogli** [comment]
Ok, I'll directly use RtMidi. Thanks btw for your responsiveness and all the work you do :). Regards.
